trigger: none
pool: Todo_Microservice_Pool




steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
    backendServiceArm: 'Todo_Infra_Connection'
    backendAzureRmOverrideSubscriptionID: '1dd58551-b1ab-46ef-9957-b05198450f53'
    backendAzureRmResourceGroupName: 'dev-rg-01'
    backendAzureRmStorageAccountName: 'rgstoragetododev'
    backendAzureRmContainerName: 'rgstoragecontainer'
    backendAzureRmKey: 'Terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
    environmentServiceNameAzureRM: 'Todo_Infra_Connection'

