trigger: none
pool: Todo_Microservice_Pool




steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
    backendServiceArm: 'Todo_Infra_Connection'
    backendAzureRmOverrideSubscriptionID: 'ba58d5e6-0957-437c-9efe-dc7469a93475'
    backendAzureRmResourceGroupName: 'Todoapp-RG'
    backendAzureRmStorageAccountName: 'brijendrastoragel'
    backendAzureRmContainerName: 'starbuckscontainer'
    backendAzureRmKey: 'Terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environments/dev'
    environmentServiceNameAzureRM: 'Todo_Infra_Connection'

