trigger: 
- main

pool: Todo_Microservice_Pool


stages: 
- stage: Init
  displayName: Build
  jobs: 
    - job: Initilization
      steps:
      - task: TerraformInstaller@1
        displayName: Terraform Install
        inputs:
          terraformVersion: 'latest'
    
      - task: TerraformTask@5
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'C:\Users\Brijendra\agent\_work\1\s\Environmets\dev'
          backendServiceArm: 'TodoApp_Service'
          backendAzureRmResourceGroupName: 'Brijendra_RG'
          backendAzureRmStorageAccountName: 'brijendrastoragelab'
          backendAzureRmContainerName: 'brijendracontainerlab'
          backendAzureRmKey: 'terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform Validate
        inputs:
          provider: 'azurerm'
          command: 'validate'


    - job: tfsec
      dependsOn: Initilization
      displayName: TfSec Scan
      steps:
      - task: tfsec@1
        inputs:
          version: 'v1.26.0'
          workingDirectory: 'C:\Users\Brijendra\agent\_work\1\s\Environmets\dev'

    - job: tflint
      dependsOn: tfsec
      displayName: TFLint
      steps:
      - task: PowerShell@2
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            winget install TerraformLinters.tflint     
            ls   
            tflint
          errorActionPreference: 'continue'        
          workingDirectory: 'C:\Users\Brijendra\agent\_work\1\s\Environmets\dev'

- stage: costStage
  dependsOn: Init
  displayName: Cost & Impact Assessment Stage
  jobs: 
    - job: InfraCost
      displayName: InfraCost
      steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: 'infracost breakdown --path=.'
          workingDirectory: 'C:\Users\Brijendra\agent\_work\1\s\Environmets\dev'
      
    - job: Plan
      displayName: Planning
      steps:
      - task: TerraformTask@5
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'C:\Users\Brijendra\agent\_work\1\s\Environmets\dev'
          backendServiceArm: 'TodoApp_Service'
          backendAzureRmResourceGroupName: 'Brijendra_RG'
          backendAzureRmStorageAccountName: 'brijendrastoragelab'
          backendAzureRmContainerName: 'brijendracontainerlab'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: 'C:\Users\Brijendra\agent\_work\1\s\Environmets\dev'
          environmentServiceNameAzureRM: 'TodoApp_Service'
          backendServiceArm: 'TodoApp_Service'
          backendAzureRmResourceGroupName: 'Brijendra_RG'
          backendAzureRmStorageAccountName: 'brijendrastoragelab'
          backendAzureRmContainerName: 'brijendracontainerlab'
          backendAzureRmKey: 'terraform.tfstate'







